name: Main workflow

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [1.26.1, 1.38.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Install rust and print rust version
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-add rust $GITHUB_WORKSPACE
          asdf install rust ${{ matrix.rust }}
          asdf global rust ${{ matrix.rust }}
          rustc --version

  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Test plugin
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-add rust $GITHUB_WORKSPACE
          bats test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run ShellCheck
        run: shellcheck bin/*
